// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgOTqEd2ua67HWMzTTqWhOxsmLdbiHL-Y',
    appId: '1:62167333879:android:594cf14b54c2e481fdccf2',
    messagingSenderId: '62167333879',
    projectId: 'mychat-9e63e',
    databaseURL: 'https://mychat-9e63e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mychat-9e63e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3YqHbjuPsl0hAgGQ3oUvqK9pe5z5esI',
    appId: '1:62167333879:ios:342bb8aafe0a9caafdccf2',
    messagingSenderId: '62167333879',
    projectId: 'mychat-9e63e',
    databaseURL: 'https://mychat-9e63e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mychat-9e63e.appspot.com',
    androidClientId: '62167333879-u0p2soj53rm38hedqge5q08td1b8f99f.apps.googleusercontent.com',
    iosClientId: '62167333879-748v89f9t1ncpleq780u39ni7fn619v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApps',
  );
}
